---
# tasks file for helloworld
- name: Copying the service set file
  copy:
    src: app-config.sh
    dest: /home/ec2-user/app-config.sh
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Execute the command in remote shell for app service setting
  shell: sudo /home/ec2-user/app-config.sh

