---
# tasks file for preconfig
- name: Installing platform software
  yum:
    name: "{{ item }}"
    enablerepo: epel
    state: installed
  with_items:
#    - python
#    - python-devel
#    - python-pip
#    - ansible
    - openssl
    - nodejs
    - npm
    - java
