---
# tasks file for preconfig
- name: Installing platform applications
  yum:
    name: "{{ item }}"
    enablerepo: epel
    state: installed
  with_items:
    - httpd 
    - docker
    - git 
    - curl

