---
# tasks file for helloworld
- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/helloworld.js
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

#- name: Copying the upstart file
#  copy:
#    src: helloworld.conf
#    dest: /etc/init/helloworld.conf
#    owner: root
#    group: root
#    mode: 0644

- name: Copying the upstart file
  copy:
    src: helloworld-service.sh
    dest: /home/ec2-user/helloworld-service.sh
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Execute the command in remote shell
# script: /home/ec2-user/helloworld-service.sh
# ansible.builtin.script: 
#   cmd: /home/ec2-user/helloworld-service.sh
  shell: /home/ec2-user/helloworld-service.sh


- name: Starting the HelloWorld node service
  service:
    name: helloworld
    state: started
