---
# tasks file for helloworld
- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/helloworld.js
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Copying the service set file
  copy:
    src: app-service-set.sh
    dest: /home/ec2-user/app-service-set.sh
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Execute the command in remote shell for app service setting
  shell: /home/ec2-user/app-service-set.sh

- name: Starting the HelloWorld node service
  service:
    name: helloworld
    state: started
